module.exports = [
    'justica',
    'tribunal',
    'uf',
    'tipoUnidade',
    'classificacaoUnidade',
    'codigo',
    'unidadeJudiciaria',
    'municipioSede',
    'telefone',
    'cep',
    'endereco',
    'unidadesJudiciarias',
    'estoque',
    'taxaCongestionamentoLiquida',
    'taxaCongestionamentoTotal',
];
